### ISSUE TITLE
Syntax inconsistency causes all widgets in project to break in IE11

### ISSUE THREAD

**Issue by rluigjes** [mendixlabs/FocusHelper#1]
In line 160 of FocusHelper.js the function is called without the ": function " part. This causes all widgets in the entire project to error in IE11.

Proposed fix: replace line 160 with:
`_setFocusOnInput: function(inputNode) {`

I'm not an expert in js, so maybe there is a reason for this, but this fixed it for me.

**Comment by tieniber** [comment]
Fixed in #6

**Comment by ahwelgemoed** [comment]
Merged and Fixed
